[project]
name = "Battery Monitor"
version = "0.0.1"
description = "Measure recharable battery statuses"
authors = ["Stefan Strömberg <stefangs@nethome.nu>"]

[project.dependencies]
psycopg2 = "^2.9.6"
pyparsing = "^3.0.7"
pyserial = "^3.5"
python-dateutil = "^2.8.2"
tabulate = "^0.8.10"


